# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  
  #vmImage: ubuntu-latest
  name: Default
  

steps:
- script: echo Debug: Checking PATH
    displayName: 'Debug: Start PATH Check'

  - script: echo %PATH%
    displayName: 'Debug: Show PATH variable'

  - script: where mvn
    displayName: 'Debug: Locate mvn'

  - script: mvn -v
    displayName: 'Debug: Maven Version Check'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
